apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  labels:
    app: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - name: hello
        image: localhost:32000/hello:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        - containerPort: 22

---
apiVersion: v1
kind: Service
metadata:
  name: hello-service
spec:
  selector:
    app: hello
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: hello-ssh-service
spec:
  selector:
    app: hello
  ports:
    - name: ssh
      protocol: TCP
      port: 2222
      targetPort: 22
  type: NodePort
