= docker

Run `hello-proxygen` in a docker container.

There are two images:

* `hello-base` : Based on `ubuntu-24.04`. Checks out and builds `proxygen` and `hello-proxygen` then runs `sshd`
* `hello` : Based on `hello-base`. Pulls latest `hello-proxygen`, builds it, then runs `sshd`


== to run docker as non-root user

```
sudo usermod -aG docker $USER
```

update current shell:

```
newgrp docker
```


== create docker images

NOTE: Failed to build proxygen in docker on ancient hardware.

=== docker build

==== build hello-base
```
docker build . -t hello-base:latest -f hello-base.docker
```

low memory:

```
docker build . -t hello-base:latest -f hello-base.docker --build-arg BUILD_JOBS=1
```

==== build hello-base

```
docker build . -t hello:latest -f hello.docker
```

=== docker buildx

==== build hello-base

```
docker buildx build -f hello-base.docker  -t hello-base:latest --load .
```

==== build hello

```
docker buildx build -f hello.docker  -t hello:latest --load .
```


== run image

Port 3000 can be any available port.

```
docker run -ti -p 3000:22 <image-id or tag>
```

=== hello-base image

```
docker run -ti -p 3000:22 hello-base:latest
```

=== hello image

```
sudo docker run -ti -p 3000:22 -p 8080:8080 hello:latest
```


=== SSH into container

The port 3000 is based on the port mapping in the `docker run` command

password:  "pass"

```
ssh ubuntu@localhost -p 3000
```

project at `/hello-proxygen/`


=== curl hello http endpoint

The port 8080 is based on the port mapping in the `docker run` command

```
curl  http://localhost::8080
```
