= docker

Run `hello-proxygen` in a docker container.

There are two images:

* `hello` : Based on `ubuntu-24.04`. Checks out and builds `proxygen` and `hello-proxygen`. Runs `sshd` for CMD[]
    ** This would need to be rebuilt for a new proxygen version.
* `hello-ci` : Based on `hello`. Pulls and builds latest `hello-proxygen`. At runtime executes `sshd`, `hello`, and `test`


== to run docker as non-root user

```
sudo usermod -aG docker $USER
```

update current shell:

```
newgrp docker
```


== create docker images

NOTE: Failed to build proxygen in docker on old hardware.

=== docker build

==== build hello
```
docker build . -t hello:latest -f hello.docker
```

low memory:

```
docker build . -t hello:latest -f hello.docker --build-arg BUILD_JOBS=1
```

==== build hello-ci

```
docker build . -t hello-ci:latest -f hello-ci.docker
```

=== docker buildx

==== build hello

```
docker buildx build -f hello.docker  -t hello:latest --load .
```

==== build hello-ci

```
docker buildx build -f hello-ci.docker  -t hello-ci:latest --load .
```


== run image

Port 3000 can be any available port.

```
docker run -ti -p 3000:22 <image-id or tag>
```

=== hello image

```
docker run -ti -p 3000:22 hello:latest
```

=== hello-ci image

```
docker run -ti -p 3000:22 -p 8080:8080 -p 8000:8000 hello-ci:latest
```


=== SSH into container

The port 3000 is based on the port mapping in the `docker run` command

password:  "pass"

```
ssh ubuntu@localhost -p 3000
```

project at `/hello-proxygen/`


=== curl hello http endpoint

The port 8080 is based on the port mapping in the `docker run` command

```
curl  http://localhost::8080
```
