= notes


== proxygen v2025.02.03.00

Moving to v2025.02.03.00 caused a link error.  Quic was moved out of proxygen to https://github.com/facebook/mvfst

Not sure when that happened but library `mvfst_exception` had to be added to the target link libraries.

Looking though the build files two other libraries look like they might needed to use quic:

----
mvfst_client
mvfst_server
mvfst_transport
----

Seems crazy but a lot of these libraries contain only one `.o` file.  


== building on wsl - ubuntu 24.04

NOTE: when clang was installed its libstdc++ dependency was missing.  This was strange because gcc was working fine.

----
sudo apt install clang libstdc++-14-dev
----


== building proxygen on rocky linux 9

NOTE: In the last clean build on rocky linux failed to build the first time.

This was a memory issue.  Increasing to 20GB fixed this.


== building on debian 12 on chromebook

There's a build option to set the number of jobs.  With the number of jobs set to 1 it build on a chromebook.

----
./build.sh -j <number-of-jobs>
----

== Future<T> functions

```
folly/futures/Future-inl.h

T Future<T>::get()
Future<T>::ensure(F&& func)
Future<T>::onTimeout(...)
Future<T> makeFuture(Try<T> t)
Future<T>::reduce()
Future<T>::within(HighResDuration dur, Timekeeper* tk)
Future<T> Future<T>::within(HighResDuration dur, E e, Timekeeper* tk)
Future<T> Future<T>::delayed(HighResDuration dur, Timekeeper* tk)

SemiFuture<T>& SemiFuture<T>::wait()
SemiFuture<int>::defer()
 
folly/futures/ThreadWheelTimekeeper.h
class ThreadWheelTimekeeper : public Timekeeper
```
