= performance test

This was made to performance test `hello` server.  It uses POST requests with a random payload.     

== usage

=== start server

Example of staring server with INFO logging turned off and a response delay of 50 milliseconds.

```bash
hello/hello --minloglevel=1 --echo_request_lag=50
```

parameters:

```
minloglevel: run server with INFO logging turned off (INFO=0, WARN=1, ERROR=2)
echo_request_lag: milliseconds to wait before sending response (default=0)
```

=== run performance test

localhost:

```bash
test/performance --number_of_requests=100 --num_connections=10
```

remote host:

NOTE: Ensure the firewall is open.  Can be verified with: `telnet <ip> <port>`

```bash
test/performance --target_host=192.168.1.107 --target_port=8080 \
  --num_connections=500 --number_of_requests=1000 --payload_size=100 \
  --connect_timeout=5000
```

example output:

```
I20250130 19:49:24.113564 71890 performance_test.cpp:172] Connecting to: http://192.168.1.107:8080/
I20250130 19:49:34.003443 71890 performance_test.cpp:186] Connected 500 HttpClient's in 9.87364 seconds
I20250130 19:49:34.266191 71890 performance_test.cpp:201]
I20250130 19:49:34.266217 71890 performance_test.cpp:202] sent 1000 HTTP POST requests
I20250130 19:49:34.266224 71890 performance_test.cpp:203] total time       : 0.262065 seconds
I20250130 19:49:34.266250 71890 performance_test.cpp:205] content size     : 100 bytes
I20250130 19:49:34.266273 71890 performance_test.cpp:206] num connections  : 500 connections
I20250130 19:49:34.266281 71890 performance_test.cpp:208] avg request Time : 0.262065 ms
I20250130 19:49:34.266286 71890 performance_test.cpp:209] request rate     : 3815.84 requests/second
I20250130 19:49:34.266290 71890 performance_test.cpp:210] bit rate         : 0.291126 Mbps
```

==== parameters

```
target_host - Host or IP address
target_port - Host port
num_connections - number of HttpClients to use for load testing
number_of_requests - number of requests
payload_size - number of bytes to send in the body of each request
connect_timeout - number of milliseconds to wait for an HttpClient to connect
```

=== results



==== payload

==== number of connections

ensure that the number of socket connections is above your testing values on BOTH the client and server machines.

```
ulimit -n <max-connections>
```

example:

```
ulimit -n 100000
```


=== factors affecting performance

How you can be misled by performance testing:

==== payload size

It's important to test with a payload that is representative of actual payloads.  If you test with 10 bytes and the actually payload is around 16k your numbers will be off.

Performance should also be tested with a max payload.  

==== response validation

 An overloaded server can do unexpected things.  Like short circuit its normal processing and send back a warning message.  I forget which tool we used but I was involved in some testing where this exact thing happened and we had impossible request rate numbers.


==== response validation
----
Performance Variables
================
Number of threads - not implemented
Number of clients - FLAGS_num_connections
Size of payload - FLAGS_payload_size
Echo or Ack with checksum - only echo for now

Performance Metrics
================
Request time
Request rate
Bit rate
Memory Footprint - not measured
----